export const MenusAndScopesEnum = {
    menus: {
        MASTERS : "MASTERS",
        PACKINGLISTCREATION : "PACKING LIST CREATION",
        SECURITYENTRANCE : "SECURITY ENTRANCE",
        UNLOADINGANDGRNPROCESS : "UNLOADING AND GRN PROCESS",
        LOCATIONUPDATION : "LOCATION UPDATION",
        INSPECTION : "INSPECTION",
        DASHBOARD : "DASHBOARD",
        REPORTS : "REPORTS"

    },
    subParentMenus: {
        WMSSYSTEMREPORTS : "WMS SYSTEM REPORTS",
        INSPECTIONREPORTS : "INSPECTION REPORTS"

    },
    subMenus: {
        PALLETROLEALLOCATION : "PALLET ROLE ALLOCATION",
        PALLETBINALLOCATION : "PALLET BIN ALLOCATION",
        INSPECTIONBOARDS : "INSPECTION BOARDS",
        FOURPOINTINSPECTION : "FOUR POINT INSPECTION",
        SHADESAGGREAGATION : "SHADE SAGGREAGATION",
        GSMINSPECTION : "GSM INSPECTION",
        SHRINKAGEINSPECTION : "SHRINKAGE INSPECTION",
        RELAXATION : "RELAXATION",
        WAREHOUSEDASHBOARD : "WAREHOUSE DASHBOARD",
        RACKDASHBOARD : "RACK DASHBOARD",
        VEHICLESDASHBOARD : "VEHICLES DASHBOARD",
        SECURITYCHECKINDASHBOARD : "SECURITY CHECK IN DASHBOARD",
        EMPTYPALLETDETAILSREPORT : "EMPTY PALLET DETAILS REPORT",
        FABRICINWARDDETAILSREPORT : "FABRIC INWARD DETAILS REPORT",
        GRNDETAILSREPORT : "GRN DETAILS REPORT",
        OPENPODETAILSREPORT : "OPEN PO DETAILS REPORT",
        FOURPOINTINSPECTIONREPORTS : "FOUR POINT INSPECTION REPORTS",
        SHADEINSPECTIONREPORTS : "SHADE INSPECTION REPORTS",
        LABINSPECTIONREPORTS : "LAB INSPECTION REPORTS",
        SHIRANKAGEINSPECTIONREPORTS : "SHIRANKAGE INSPECTION REPORTS",
        RELAXATIONINSPECTIONREPORTS : "RELAXATION INSPECTION REPORTS"

    },
    scopes: {
        CREATE: 'CREATE',
        UPDATE: 'UPDATE',
        DELETE: 'DELETE',
        VIEW: 'VIEW',
        EXPORT_EXCEL: 'EXPORT_EXCEL',
        EXPORT_PDF: 'EXPORT_PDF',
        UPLOAD_EXCEL: 'UPLOAD_EXCEL',
    },
    roles: {

    }

}
