export enum PkmsFgWhCurrStageEnum {
    OPEN = "OPEN",
    SECURITY_IN = "SECURITY IN",
    PRINT = "PRINT",
    FG_IN_PROGRESS = "FG IN PROGRESS",
    FG_IN_COMPLETE = "FG IN COMPLETE",
    PALLET_MAP_PROGRESS = "PALLET MAP PROGRESS",
    PALLET_MAP_COMPLETED = "PALLET MAP COMPLETED",
    LOC_MAP_PROGRESS = "LOC MAP PROGRESS",
    LOC_MAP_COMPLETED = "LOC MAP COMPLETED",
    LOC_UNMAP_PROGRESS = "LOC UNMAP PROGRESS",
    LOC_UNMAP_COMPLETED = "LOC UNMAP COMPLETED",
    S_OUT = "S OUT",
    FG_OUT_PROGRESS = "FG OUT PROGRESS",
    FG_OUT_COMPLETE = "FG OUT COMPLETE",
    APPROVED = "APPROVED",
    REJECTED ="REJECTED"
  }