import { Column, Entity } from "typeorm";
import { AbstractEntity } from "../../../database/common-entities";
import { ContainerSubItemReadinessEnum, DispatchEntityEnum } from "@xpparel/shared-models";


@Entity('d_set_sub_item')
export class DSetSubItemEntity extends AbstractEntity {

    @Column("bigint", { name: "d_set_id", nullable: false, comment: 'pk of the d_set table' })
    dSetId: number;

    @Column("bigint", { name: "d_set_item_id", nullable: false, comment: 'pk of the d_set_item table' })
    dSetItemId: number;

    @Column("varchar", { length: "5", name: "dispatch_entity", nullable: false, comment: 'The entity type being dispatched (electronics/garment/etc)' })
    dispatchEntity: DispatchEntityEnum;

    // The PK of the ADB shade table in cps
    @Column("varchar", { length: "8", name: "de_ref_id", nullable: false, comment: 'The pk of the  de ref table. Currently PK of adb_shade' })
    deRefId: string;

    /**
     * ref1: PK of the po_docket_lay
     * ref2: under lay bundle no
     * 
     */
    @Column("varchar", { length: "30", name: "de_ref_no1", nullable: false, comment: 'item related ref number , could be cut/docuket/style/schedule/some other no .Currently PK of the po_docket_lay' })
    deRefNo1: string;

    @Column("varchar", { length: "30", name: "de_ref_no2", nullable: true, comment: 'item related ref number , could be cut/docuket/style/schedule/some other no. Currently under lay bundle no' })
    deRefNo2: string;

    @Column("varchar", { length: "30", name: "item_no", nullable: true, comment: 'item related ref number , could be cut/docuket/style/schedule/some other no  ' })
    itemNo: string;

    @Column("varchar", { length: "20", name: "barcode", nullable: false, comment: 'generated by system/existing barcode' })
    barcode: string;

    @Column("varchar", { name: "item_readiness", length: 5, nullable: false, comment: 'The item readiness number for  dispatch' })
    itemReadiness: ContainerSubItemReadinessEnum;

    @Column("decimal", { scale: 2, precision: 7, name: "item_quantity", nullable: false, comment: '' })
    itemQuantity: number;

    @Column("tinyint", { name: "print_status", nullable: false, comment: 'The print status for  dispatch', default: 0 })
    printStatus: number;
}