import { Column, Entity } from "typeorm";
import { AbstractEntity } from "../../../database/common-entities";
import { ShippingRequestProceedingEnum, ShippingRequestStageEnum } from "@xpparel/shared-models";

@Entity('s_request')
export class SRequestEntity extends AbstractEntity {

    @Column("varchar", { length: "15", name: "request_no", nullable: false, comment: 'The autogenerated request number system generated/user generated number' })
    requestNo: string;

    // TODO
    @Column("varchar", { name: "current_stage", length: 5, nullable: false, comment: 'The current stage' })
    currentStage: ShippingRequestProceedingEnum;

    @Column("text", { name: "remarks", nullable: false, comment: 'The shipping req remarks' })
    remarks: string;

    @Column("tinyint", { name: "print_status", nullable: false, comment: 'The print status for  dispatch', default: 0 })
    printStatus: number;
}