export * from './gb-department-req.dto';
export * from './gb-section-req-dto';
export * from './gb-get-all-departments-res-dto';
export * from './gb-get-all-departments-res-modal';
export * from './gb-get-all-sections-res-dto';
export * from './gb-get-all-sections-res-modal';
export * from './gb-get-all-locations-res-dto';
export * from './gb-get-all-locations-res-modal';
export * from './gb-section-model';
export * from './gb-section-response';
export * from './gb-section-req';
export * from './gb-location-model';
export * from './gb-location-req';
export * from './gb-location-response'
