export enum AllIns {
    PRE_INSPECTION = 'PRE_INSPECTION',
    POST_INSPECTION = 'POST_INSPECTION',
    INSPECTION = 'INSPECTION',
    SHADE_SEGREGATION = 'SHADE SEGREGATION',
    LAB_INSPECTION = 'LAB INSPECTION',
    RELAXATION = 'RELAXATION',
    SHRINKAGE = 'SHRINKAGE',
}