export enum InsRequestStatusEnum {
    PENDING_REQUESTS = 'PENDING REQUESTS',
    ACKNOWLEGE = 'ACKNOWLEGE',
    IN_PROGRESS = 'IN PROGRESS',
    COMPLETED = 'COMPLETED'
}

export const InsRequestStatusEnumDisplayValue= {
    PENDING_REQUESTS: 'PENDING REQUESTS',
    ACKNOWLEGE: 'ACKNOWLEGED REQUESTS',
    IN_PROGRESS: 'IN PROGRESS REQUESTS',
    COMPLETED: 'COMPLETED REQUESTS'
}