export enum InsTrimDefectTypesEnum {
    BROKEN_BUTTON = 'Broken Button',
    RUST = 'Rust',
    COLOR_MISMATCH = 'Color Mismatch',
    TEAR = 'Tear',
    STITCHING_ISSUE = 'Stitching Issue',
    LOOSE_THREAD = 'Loose Thread',
    MISSING_PART = 'Missing Part',
    WRINKLED = 'Wrinkled',
    FADED_COLOR = 'Faded Color',
    PUNCTURE = 'Puncture',
    IMPERFECT_SEAM = 'Imperfect Seam',
    BUTTON_FALLING_OFF = 'Button Falling Off',
    ZIPPERS_ISSUE = 'Zipper Issue',
    STAIN = 'Stain',
    DEFECTIVE_LABEL = 'Defective Label',
    DAMAGED_TAG = 'Damaged Tag',
    LOOSE_ELASTIC = 'Loose Elastic',
    DAMAGED_RIB = 'Damaged Rib',
    PEELED_TAPE = 'Peeled Tape',
    EMBELLISHMENT_ISSUE = 'Embellishment Issue',
    OTHER = 'Other',
}
