export enum BULLJSQUEUENAMESTOMODULEMAP {
    CPS_DOC_BUN_GEN = 'CPS',
    CPS_PO_DOC_SER_GEN = 'CPS',
    CPS_DOC_BUN_PANEL_GEN = 'CPS',
    CPS_DOC_CON = 'CPS',
    CPS_UN_LOCK_DOC_MATERIAL = 'CPS',
    CPS_CUT_NUMBER_GEN = 'CPS',
    CPS_UPDATE_ALLOC_FAB_TO_EXT_SYS = 'CPS',
    CPS_UPDATE_ISSUE_FAB_TO_EXT_SYS = 'CPS',
    CPS_POPULATE_CUT_FGS = 'CPS',


    ETS_EMB_REQ_GEN = 'ETS',
    ETS_EMB_HEADER_DEL = 'ETS',
    ETS_EMB_LINE_DEL = 'ETS',
    ETS_EMB_OP_QTY_UPD = 'ETS',
    PACK_FG_POPULATION = 'PKMS'
}
