export enum CPS_BULLJSJOBNAMES {
    CPS_DOC_BUN_GEN = 'CPS_DOC_BUN_GEN',
    CPS_PO_DOC_SER_GEN = 'CPS_PO_DOC_SER_GEN',
    CPS_DOC_BUN_PANEL_GEN = 'CPS_DOC_BUN_PANEL_GEN',
    CPS_DOC_CON = 'CPS_DOC_CON',
    CPS_UN_LOCK_DOC_MATERIAL = 'CPS_UN_LOCK_DOC_MATERIAL',

    CPS_LAY_CUT_REP = 'CPS_LAY_CUT_REP',
    CPS_DB_CUT_REP = 'CPS_DB_CUT_REP',
    CPS_LAY_CUT_REV = 'CPS_LAY_CUT_REV',

    CPS_PEN_ROLLS_TO_ONFLOOR = 'CPS_PEN_ROLLS_TO_ONFLOOR',
    CPS_UPDATE_CONSUMED_FAB_TO_EXT_SYS = 'CPS_UPDATE_CONSUMED_FAB_TO_EXT_SYS',
    CPS_CUT_NUMBER_GEN = 'CPS_CUT_NUMBER_GEN',

    CPS_UPDATE_ALLOC_FAB_TO_EXT_SYS = 'CPS_UPDATE_ALLOC_FAB_TO_EXT_SYS',
    CPS_UPDATE_ISSUE_FAB_TO_EXT_SYS = 'CPS_UPDATE_ISSUE_FAB_TO_EXT_SYS',

    CPS_POPULATE_CUT_FGS = 'CPS_POPULATE_CUT_FGS'

}

/**
 * CON - confirmation
 * GEN - generation
 * DEL - deletion
 * REP - Reporting
 * REV - Reversal
 * PEN - PENDING
 * 
 */